version: "3.8"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      - REPLICA_URLS=http://replica1:8001,http://replica2:8002,http://replica3:8003
    depends_on:
      - replica1
      - replica2
      - replica3

  replica1:
    build: ./replica1
    container_name: replica1
    ports:
      - "8001:8001"
    environment:
      - ID=1

  replica2:
    build: ./replica2
    container_name: replica2
    ports:
      - "8002:8002"
    environment:
      - ID=2

  replica3:
    build: ./replica3
    container_name: replica3
    ports:
      - "8003:8003"
    environment:
      - ID=3

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - gateway